file = open('example_utf8.txt', 'w+', encoding='utf-8')
file.write("Текст на русском языке.\n")
file.write("More text in UTF-8.\n")
file.seek(0)
content = file.read()
print(content)
file.close()